faq = {
    "What is ALAT": "ALAT by Wema is Wema Bank fully Digital Banking Platform that allows you conduct all your banking transactions without ever having to visit any physical branch",
    "Who can use ALAT": "Everyone! you simply need to get registered on a smartphone. To operate your account, you may use your smartphone or revert to the *945# USSD banking.",
    "How much does it cost to get ALAT": "ALAT is free to sign up on.",
    "Which mobile platforms are supported by the ALAT Application": "The ALAT is currently supported on all IOS and Android devices. Please visit your Google Play store or App Store to download the application.",
    "Can I create goals on ALAT": "Yes, goals creation is allowed for all tier three savings and current account holders on ALAT.",
    "What type of goals can I create on ALAT": ["We have 3 variants of goals on ALAT", 
                                                "Fixed Goal: You can save daily, weekly or monthly towards a target amount with no withdrawals allowed. You also qualify for interest when you meet the target amount you set",
                                                "Flexi Goal: You can save daily, weekly or monthly towards a target amount with 50% withdrawal allowed on the amount saved. You also qualify for interest when you meet the target amount you set",
                                                "Stash : You can save whatever you want, whenever you want, no withdrawal allowed. You also qualify for interest on your savings after 30 days, You can earn up to 10% interest per annum on your Goal savings.",
                                                ],
    "What is the highest amount I can save on goals": "NGN 999,999,999", 
    "How to register on ALAT": [
                                    "Open app to landing page.",
                                    "Click get started.",
                                    "Click Continue on value proposition page.",
                                    "Validate BVN",
                                    "- Enter BVN",
                                    "- Take photo of face",
                                    "- Take photo of signature",
                                    "- If BVN facial match fails, OTP would be sent to a new customer's BVN phone number and used as an alternative for validating BVN.",
                                    "- OTP would be sent to existing WEMA Bank customer's BVN phone number and used as an alternative for validating BVN.",
                                    "Create Profile",
                                    "- Enter email",
                                    "- Enter password",
                                    "- Confirm password",
                                    "Secure Your account",
                                    "- Choose security question",
                                    "- Answer security answer",
                                    "- Enter referral code",
                                    "Get to ALAT Dashboard and get Account number.",
                                    "New to bank customers follow prompts to upgrade account:",
                                    "- Create PIN",
                                    "- Update residential address",
                                    "- Upload ID" 
                                ],
"Wallet customers on ALAT": [
                                "Starting the process:",
                            	"- Open app to landing page.",
                            	"- Click get started",
                                "- Click “Continue” on value proposition page",
                                "Initiating Wallet:",
                            	"- Click 'Skip BVN' on BVN validation page",
                                "Enter Wallet details:",
                            	"- Phone number",
                                "- First name",
                            	"- Last name",
                            	"- Middle name (optional)",
                            	"- Gender",
                            	"- Date of birth",
                            	"- Validate OTP to phone number.",
                                "Create Profile",
                            	"- Enter email",
                            	"- Enter password",
                            	"- Confirm password",
                                "Secure your account",
                            	"- Choose security question",
                            	"- Answer security answer",
                                "- Enter referral code",
                                "Get to ALAT Dashboard and get Wallet number.",
                                "Upgrade wallet later to account", 
                                "Link BVN"
                                ],
"Can I take loan on my goals": [
                                    "Yes. You are entitled to a goal-based loan of up to 80% of the amount saved on goals at an interest of 20% per annum.",
                                    "On the ALAT application",
                                    "- Click on the 'Forgot Password' option",
                                	"- Enter your registered email address or username and click next",
                                	"- Enter new password, and confirm new password entry.",
                                	"- Validate with ALAT PIN or Security Answer",
                                	"- Receive OTP on registered phone number and input in OTP segment",
                                	"- Click Submit",
                                	"- Login with new password",
                                    "You need to have access to your registered Phone number to successfully reset your forgotten password"
                                ],
"How to create an ALAT GOAL": [
                                    "- Log into ALAT application using your registered email address and password",
                                	"- Select “Goals” on the Home Page",
                                	"- Select your preferred savings type from either Personal Savings or Group Savings", 
                                    "For Personal Savings",
                                	"- Select one of Fixed, Flexi or Stash Goals",
                                	"- Fill in the required fields and select 'Next'",
                                	"- Review input and select 'Create Goal'", 
	                                "For Group Savings",
                                	"- Select Preferred savings type or 'Join a group'",
                                	"- Fill in the required fields (Group Code for Group Savings) and select 'Next'",
                                	"- Review input and select 'Create Goal'", 
                                    "- Note: Up to 12 users can perform a Group Savings on ALAT"
                                ],
"How to perform ALAT PIN reset": [
                                    "Log into ALAT application using your registered email address and password"
                                	"- Click on 'Settings' and tap on 'ALAT Pin Management'",
                                	"- Click on 'Forgot ALAT Pin'",
                                	"- Input the answer to your Security Question",
                                	"- Receive OTP in registered email address and input in OTP segment",
                                	"- Input New Pin and Confirm New Pin",
                                    "- Click Submit",
                                    "You need to have access to your registered Email address to successfully reset your ALAT PIN"
                                ],
"How to Hotlist my ALAT card": [
                                    "Log into ALAT application using your registered email address and password"
                                	"- Select 'Cards' on Home Page",
                                	"- Select 'My Cards'",
                                	"- Select 'Hotlist Card'",
                                	"- Select a reason for Card Hotlist on the list",
                                	"- Input ALAT PIN and select Hotlist",
                                    "You can Hotlist your ALAT card if it is lost, stolen, damaged or if you suspect any fraudulent activity on your account."
                                ]
}


